[package]
name = "rustplot"
version = "0.1.0"
edition = "2021"
author = "rudolf slusarski"
readme = "README.md"
repository = "https://github.com/rudolf-slusarski/rustplot"

[dependencies]
image = "0.24.3"