[package]
name = "rustplot"
version = "0.1.0"
author = "rudolf slusarski"
edition = "2021"
license = "MIT"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/rudolf-slusarski/rustplot"

[dependencies]
svg = "0.12.0"

[dev-dependencies]
rand = "0.8.5"